### PR TITLE
Added main to otkit-icons

### PR DESCRIPTION
**Pull request by antwhite**
Fixes issues when importing the package  and webpack DLL pipeline

### CODE REVIEW

**Comment by seif** [comment]
@lastquestion how much later? :D

**Comment by lastquestion** [comment]
Wow, LOL. Luckily, I have managed to delegate this entire problem to @mannionaco and @karuto :)

**Comment by lastquestion** [comment]
This is a nice fix too. Still have the same problem though, @karuto

**Comment by seif** [comment]
What is the problem?

**Comment by seif** [comment]
@lastquestion I merged it, I guess it will published with next icon update.

**Comment by karuto** [comment]
@seif @chriscartlidge @lastquestion I will manually publish a major version after this merge.

**Comment by seif** [comment]
Thanks @karuto curious why the major bump, what scenario would this be a breaking a change for?  
7.2.0 already included the change in this PR https://github.com/opentable/design-tokens/commit/c0822839fb37059a369893e6aad7ada1aa394dba

**Pull request merged**
