### PR TITLE
adding Points icon

### PR DESCRIPTION
**Pull request by mannionaco**

### CODE REVIEW

**Comment by nicotaing** [comment]
@matteofigus @nickbalestra when you have a chance, can you guys add that new icon? Will need it after memorial week end :)

**Comment by nickbalestra** [comment]
It should be added and published automatically upon merging

**Comment by nicotaing** [comment]
👍

**Comment by nickbalestra** [comment]
@nicotaing -> in [v1.1.0](https://github.com/opentable/design-tokens/releases/tag/otkit-icons%401.1.0)

**Pull request merged**
