### PR TITLE
updating xlarge and large

### PR DESCRIPTION
**Pull request by mannionaco**
xlarge 32px to 28px, line-height 40px to 36px
large 24px to 22px, line-height 32px to 28px

### CODE REVIEW

**Comment by lastquestion** [comment]
@karuto can you take care of merging this as a major release? thanks!

**Comment by karuto** [comment]
@lastquestion what do you mean by "merging this as a major release", aren't the version updates done by devops bot automatically now?

**Comment by lastquestion** [comment]
the build script would make this a patch change, because we only changed the value. but I think this is a breaking change so it should be a major change.

**Comment by karuto** [comment]
@lastquestion I agree that this is a major change in theory, but not sure about the execution. Should we manually change the major version in package.json?

**Comment by lastquestion** [comment]
that would be insufficient. i would probably merge this PR into a local master, publish from there, and push that master up to remote master. the build script will still run, but since you already published there will be no changes.

**Comment by karuto** [comment]
@lastquestion This commit has been manually merged into [master.](https://github.com/opentable/design-tokens/commits/master)

[A new release](https://github.com/opentable/design-tokens/releases) is also created.

Changes also published to [npmjs registry.](https://www.npmjs.com/package/otkit-typography-desktop)

**Pull request merged**
