### PR TITLE
Create mobile web typography token, change xlarge + xxlarge

### PR DESCRIPTION
**Pull request by karuto**
This PR is a result of discussion thread https://github.com/opentable/design-tokens/issues/91, seems like we reach agreement on the following action items:

* create a new xxlarge values in https://github.com/opentable/design-tokens/blob/master/OTKit/otkit-typography/token.yml
* change the xlarge values in https://github.com/opentable/design-tokens/blob/master/OTKit/otkit-typography/token.yml
* create a new xxlarge font group in https://github.com/opentable/design-tokens/blob/master/OTKit/otkit-desktop-typography/token.yml
* create a new set of font groups (that are not unique, e.g. are same as web) in a new package otkit-mobile-typography

The mobile web font group values are from the typography stack image: https://github.com/opentable/design-tokens/issues/91#issuecomment-363507564.

Questions for @mannionaco and @francesyun:
 * We gave semantic names to font groups in desktop web, such as `heading-[size]`, `bodytext-[size]` etc. Can you advise on the mobile web ones?
 * In the typography stack image, seems like mobile web and desktop web have different definitions of xsmall and small. I would like to hear your inputs before putting them in. Inside ` OTKit/otkit-mobileweb-typography`, we have 2 ways of assigning them:

1. We reuse the shared pool of already defined variables, but may cause confusion:
```
  bodytext-small-font-size:
    type: "size"
    value: "{!font-size-xsmall}"
```
2. We define a new value locally, straight forward but missing the reusability:
```
  bodytext-small-font-size:
    type: "size"
    value: "14px"
```
I personally leaning towards the approach in 2, but this makes me question the purpose of `OTKit/aliases.yml` because it exists in a desktop-centric worldview.

Speaking of which, we should think about what's the purpose of `otkit-typography` token going forward. Fear that it will turn into legacy, as we create more of these platform specific tokens. Feel free to chime in from a design perspective @francesyun and @mannionaco. I'll create a separate issue if people would like to discuss.

### CODE REVIEW

**Comment by karuto** [comment]
This PR will not be worked on until we get a clear feedback from design about the future of platform typography, the balance between unification vs divergence, etc.

**Comment by mannionaco** [comment]
We have chosen to have two type ramps. One for Web (desktop, tablet) and a second for Mobile (mWeb, iOS, Android). Web is composed of only our brand font, Brandon Text. Mobile is composed of our brand font + system font. 

We decided to use system fonts within mobile because we know that audience quite well (mostly iOS users) and knowing that system fonts are built specifically for those mobile devices made it easier to decide on that direction, let alone potential performance and experiential (ex. "the font flash") benefits. On a level of value and impact Brandon Text's style is noticeable at larger sizes, less noticeable at smaller sizes.

I see a future where we may merge this POV with our Web typography, but as I see it today if we were to use system fonts within Web the variability is exponentially more difficult to control compared to mobile (ex. users seeing Arial, a font I can't subjectively allow to happen). If I am wrong let's work on a merged font library at a later date with a more robust font stack (ex. LinkedIn). 

I don't see any additional type ramps being created within the consumer experience, nor do I see the restaurant product teams using a different set. Though we will evolve this, but creating isolated font libraries to just create them goes against our unification goal. However, we will deviate with intention with appropriate rational.

When it comes to the different sizes and names demonstrated here:
https://opentable.invisionapp.com/boards/E53ARCZ736G/

I wasn't sure what would be helpful and used this to demonstrate what is shared and how System Fonts (ex. San Francisco, Android) are optically larger (roughly 15%) than our brand font Brandon Text. I don't think they need to be different. I wasn't sure what to do tbh.

I moved around the comparison graphic: 
https://opentable.invisionapp.com/boards/BR3ARCZ8VJG/

Is this helpful? Small in Mobile serves the same purpose as Small in Desktop. 

Does this information help inform the decision you mention above? May there is a mobile font library and desktop font library?

**Comment by char1e5** [comment]
cc @lastquestion @matteofigus 😃

**Comment by lastquestion** [comment]
@char1e5 please see the issue #142 :)

**Comment by karuto** [comment]
Love the conversations we are having, but I realized that I'm trying to do too much in this one PR, which caused it to turn stale. I am closing this in favor of https://github.com/opentable/design-tokens/pull/145, which does half of what this PR wants to do, but will get merged faster.

**Pull request closed without merging**
