### PR TITLE
adding metric change icons

### PR DESCRIPTION
**Pull request by mannionaco**
up and down

### CODE REVIEW

**Comment by lastquestion** [comment]
@mannionaco let's get a designer to approve and then we can merge.

**Comment by mannionaco** [comment]
I need to re-upload new edited icons, what's the best way to do that?

**Comment by lastquestion** [comment]
@mannionaco you just commit the changes again and push it up again. Did you do this via the web UI?I'm not sure how to add a new commit to the branch in the web UI, but we can try together. You can also just close this PR and open a new one.

**Comment by lastquestion** [comment]
Closing in favor of #227

**Pull request closed without merging**
