### PR TITLE
changed primary and secondary colors

### PR DESCRIPTION
**Pull request by lindseyhight**
Secondary and primary are currently the same, pending new color from brand in future

### CODE REVIEW

**Comment by nickbalestra** [comment]
@lindseyhight can you please provide some context here? What is the rationale of having primary and secondary the same? Could be a viable option to just remove the secondary until we have one and tag this release as a braking change, and then release a a new minor again once we do have it? (As i don't think people will use a secondary if its the same of a primary, this should help misuse) @lastquestion what you suggest as strategy for handling such releases, and this very specific case?

**Comment by lindseyhight** [comment]
@nickbalestra we already had spec'd some elements in secondary, but I'll just ask the team to update that token everywhere to primary and then we can remove the secondary token until we have one like you suggested.

**Comment by lastquestion** [comment]
@nickbalestra I agree with your feelings. I think it would be good to publish a breaking change version with just `primary`. We'll practice pushing design choice changes through the system via this change, which is also important. 

could you work with @lindseyhight to change this PR to do that?

**Comment by nickbalestra** [comment]
Good idea @lastquestion !
@lindseyhight as we don't have yet an automatic way to publish will be important to state in the PR title that this is a braking change, something like `[BRAKING CHANGE] - your title` could work. This will make clear for who's in charge of publishing that will need to publish that specific token as a major version in this case. Maybe specifying why/what the braking change is in the description could also a good practice.

versions works like this:
```
MAJOR version: when you make incompatible changes,
MINOR version: when you add functionality in a backwards-compatible manner, and
PATCH version: when you make backwards-compatible bug fixes.
```

In this case will be a MAJOR version.

@lindseyhigh Could you try changing this pr to reflect on those suggestion? (feel free to reachout on hipchat if you need any help)

**Pull request merged**
