### PR TITLE
introduced pixel value design tokens for layout of new restaurant profile

### PR DESCRIPTION
**Pull request by ericz82**
When setting `width`, `height` and conditions for media queries, we want to avoid hard-coding the pixel values and instead have them live here as design tokens. Let me know what your thoughts are.

### CODE REVIEW

**Comment by lastquestion** [comment]
I think we should store RP-specific values somewhere in the restaurant profile code. However, if we do have site or design wide values, such as the breakpoints from full desktop to tablet to mobile, those should definitely live here. The name `otkit-layout` seems to make sense, if we do indeed have values that should exist across the design system.

cc @mannionaco cc @lindseyhight

**Comment by lastquestion** [comment]
I'm also not sure if we should store the breakpoint value as a string or number. It is probably best to store it as an number because then we can do (easy) math on it in both JS and CSS (and other formats, too).

**Comment by ericz82** [comment]
For now just have `breakpoint-desktop-tablet` as a token then? I currently have that as a ticket.

**Comment by lastquestion** [comment]
I'd like to have design's input here and ask what from their perspective is going to be shared across pages before we decide on what to introduce.

**Comment by lindseyhight** [comment]
We have designed for breakpoints at tablet and mobile and intend to utilize these across the site in future.

**Comment by ericz82** [comment]
For now I will just have `breakpoint-desktop-tablet`

**Comment by lastquestion** [comment]
This seems reasonable, @nickbalestra what's your thoughts on putting it in a new module? Shall we just put it in `spacing`?

**Comment by nickbalestra** [comment]
Great job @ericz82 ! What about simply calling it `otkit-breakpoints`.
I think it totally make sense to have it.

**Comment by ericz82** [comment]
Sure, since we are only going to be using it for the site-wide breakpoints, `otkit-breakpoints` works for the name.

**Comment by ericz82** [comment]
I currently don't know the tablet to mobile breakpoint value or if we would even have a use for it here, but @lindseyhight or any other designer can add it if it becomes appropriate.

**Comment by nickbalestra** [comment]
@ericz82 I guess you would want to put in your personal details for the `author` field in the manifest :)

**Comment by lastquestion** [comment]
Looks great, let's merge this.

**Pull request merged**
