### PR TITLE
This is a duplicate

### PR DESCRIPTION
**Pull request by mannionaco**
removing...

### CODE REVIEW

**Comment by mannionaco** [comment]
How do I remove duplicated icons?

**Comment by matteofigus** [comment]
@mannionaco I think you really need to remove the file - not sure you can do it purely from the UI. Perhaps you can pair with @francesyun for that?

**Comment by matteofigus** [comment]
I am closing this as I see you erroneously already pushed it to master. I already made another PR for the fix so I am closing this.

**Comment by ArnoldZokas** [comment]
It is possible to remove file via Github UI. Navigate to a file and look for a recycle bin icon in the top right corner.

**Comment by matteofigus** [comment]
Oh, thanks @ArnoldZokas 👍

**Comment by mannionaco** [comment]
@matteofigus @ArnoldZokas thanks!

**Pull request closed without merging**
